spring:
  datasource:
    url: jdbc:mysql://mysql:3306/bot?useSSL=false&serverTimezone=GMT&allowPublicKeyRetrieval=true
    username: root
    password: password
    driver-class-name: com.mysql.cj.jdbc.Driver
  redis:
    host: redis
    port: 6379
  cache:
    ehcache:
      config: classpath:ehcache.xml

logging:
  level:
    root: warn

mybatis:
  type-aliases-package: top.tgchatmanager.entity
  mapper-locations: classpath:top/tgchatmanager/mapper/*.xml